# vim:syntax=yaml
version: 2
jobs:
  build_fedora:
    docker:
      - image: fedora:33
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y --nodocs \
              avahi-devel \
              boost-devel \
              clips-devel \
              clipsmm-devel \
              gcc-c++ \
              gecode-devel \
              git \
              glibmm24-devel \
              gtkmm30-devel \
              libmodbus-devel \
              mongodb-devel \
              ncurses-devel \
              openssh-clients \
              openssl-devel \
              protobuf-compiler \
              protobuf-devel \
              which \
              yaml-cpp-devel
      - checkout
      - run: make all FAIL_ON_WARNING=1
  build_ubuntu:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get -y install software-properties-common
            add-apt-repository -y ppa:timn/clips
            apt-get update
            apt-get -y install \
              libboost-all-dev \
              clips \
              git \
              libavahi-client-dev \
              libclips-dev \
              libclipsmm-dev \
              libgecode-dev \
              libglibmm-2.4-dev \
              libgtkmm-3.0-dev \
              libmodbus-dev \
              libmodbus-dev \
              libmongoclient-dev \
              libncurses5-dev \
              libncursesw5-dev \
              libprotobuf-dev \
              libprotoc-dev \
              libssl-dev \
              libyaml-cpp-dev \
              protobuf-compiler
      - checkout
      - run: make all FAIL_ON_WARNING=1
workflows:
  version: 2
  build:
    jobs:
      - build_fedora
      - build_ubuntu
